# ── Build stage ──
FROM node:18-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build

# ── Serve stage ──
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY  frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80