# Generated by Django 6.0.1 on 2026-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_attachment_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
