# Generated by Django 6.0.1 on 2026-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_attachment_file_size_attachment_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
