# Generated by Django 5.2.12 on 2026-03-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_incident_escalated_at_incident_escalated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEAM_ADMIN', 'Team Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TEAM_ADMIN', 'Team Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField()),
                ('impact', models.TextField()),
                ('resolution', models.TextField()),
                ('prevention', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postmortems', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postmortem', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incidents.team'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incident_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority'], name='incident_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assigned_to'], name='incident_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reported_by'], name='incident_reported_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_overdue'], name='incident_overdue_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_escalated'], name='incident_escalated_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='incident_created_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='incident_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['team'], name='incident_team_idx'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='incidents.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user', 'team')},
        ),
    ]
